version: "3.8"
services:
  web:
    build: ./web
    ports:
      - "8000:8000"
  api:
    build: ./apis
    ports:
      - "5000:5000"
  llm:
    build: ./llm
    ports:
      - "8080:8080"
  tcp:
    build: ./network
    ports:
      - "9001:9001"
