worker_processes 1;

events { worker_connections 1024; }

http {
  sendfile on;

  upstream web_app { server web:8000; }
  upstream api_app { server api:5000; }
  upstream ai_app { server ai:8080; }
  upstream net_app { server network_http:9101; }
  upstream cloud_app { server cloud_app:9100; }

  server {
    listen 80;

    location /labs/web/ {
      proxy_pass http://web_app;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /labs/api/ {
      proxy_pass http://api_app;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /labs/ai/ {
      proxy_pass http://ai_app;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /labs/network/ {
      proxy_pass http://net_app;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /labs/cloud/ {
      proxy_pass http://cloud_app;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
      return 200 "Playbox gateway. Use /labs/web/, /labs/api/, /labs/ai/, /labs/network/, /labs/cloud/\n";
    }
  }
}
